<MyRoot>:
    random_label: random_label
    BoxLayout:
        orientation: 'vertical'
        Label:
            text: "Sunshine"
            font_size: 200
        Label:
            id: random_label
            text: "_____"
            font_size:64
        Button:
            text: "Generate"
            font_size: 32
            size: 100, 50
            on_press: root.generate_number()